### ISSUE TITLE
Players can bring inventory from creative world to survival world by pressing 'E'

### ISSUE THREAD

**Issue by 1337ingDisorder** [Multiverse/Multiverse-Inventories#161]
I've been informed by a player on my server that there's a glitch with version 2.5-b335 of Multiverse-Inventories wherein players can bring infinite resources from one world into the other, circumventing Multiverse-Inventories' efforts to keep the two worlds' inventories separate.

I've tested this and can confirm that it can be reproduced, the technique is a little tricky to master but it works every time once you get it right.

Essentially it's just a matter of timing:

1) go into the Creative Mode world

2) Load up your personal inventory with emerald blocks, spawn eggs, and all sorts of other goodies that completely throw off the economy and game-play in the Survival Mode world

3) Warp, teleport, or use a Multiverse Portal to move into the Survival Mode world. Just as the world is changing over, hit the 'E' key to bring up your inventory GUI window.

Voila! You now have your full personal inventory from the Creative World. Now you can spend those emeralds, spawn those creepers, and generally run amok in the Survival World.

Versions:

Bukkit: git-Bukkit-1.4.7-R1.0-94-g141dcf0-b2735jnks (MC: 1.5.1)
Multiverse-Core: 2.5-b641 (beta)
Multiverse-Inventories: 2.5-b335
Multiverse-Portals:  2.4-AB
(though the glitch works even with Multiverse-Portals disabled, when users teleport or warp from one world to the other)

Server:

CentOS 5.5
2GB Dedicated RAM
80GB HDD
Excellent bandwidth (hosted on RackspaceCloud)

**Comment by TimohStudios** [comment]
2015 and still no change

**Comment by FlarupsPige** [comment]
Something new about it?

**Comment by Miclebrick** [comment]
I'm getting this bug on my server as well. I have no idea what to do about it, but this is a very, very big bug.

**Comment by dumptruckman** [comment]
I have looked into this several times and have been unable to find any solution to the problem. I realize this is a very critical problem but unless someone has some ideas on how to fix it then it's not going to be fixed.

**Comment by DevTron** [comment]
Unload inventory from client before the world change occurs?

**Comment by dumptruckman** [comment]
The problem with that is that the world change is already occurring by the time i would be able to do that.

**Comment by Miclebrick** [comment]
Strangely, I'm not getting this issue on my local test server - only on the live server.

**Comment by Miclebrick** [comment]
I am also getting players whose inventories are randomly crossing between worlds - e.g. their Survival inventory got into Spawn, their jail inventory got into Towny, their Towny inventory got into Survival - this is resulting mostly in loss of items.

**Comment by dumptruckman** [comment]
Alright @Miclebrick I added your potential fix. I'm not sure anyone is even using this plugin anymore but if someone could absolutely confirm that [build #416](https://ci.onarandombox.com/job/Multiverse-Inventories/416/) fixes the exploit I may consider reviving the plugin.

**Comment by dumptruckman** [comment]
Just to add a bit more... I need someone that was able to reproduce this bug reliably before, since I was never able to reproduce it, that can no longer reproduce it in the new build.

My current thoughts on why this bug exists is latency. This could explain why people (including myself) were unable to reproduce it on a test server since those servers are likely on a local lan or even the same machine. It could also explain why servers with more plugins are more likely to experience the bug since having more plugins could potentially reduce the TPS on the server.

**Comment by dumptruckman** [comment]
This is absolutely related to latency. Was never able to reproduce on local test server. Tried it on a friend's dev server and I could reproduce it every single time.

**Comment by dumptruckman** [comment]
I have confirmed that this exploit is no longer reproduceable in the latest dev builds!

**Comment by Beaupedia** [comment]
YES! Thank you so much!

--
Beau

**Comment by dumptruckman** [comment]
Don't get too excited. Still quite a few other critical bugs to fix...

**Comment by ScuroK** [comment]
did anyone here test this "fix"?
Because PWI has the same problem right now so he tried to fix it like you guys. But i tested it and it didnt work. 
@dumptruckman 
Did you do take any other steps rather than closing the inventory on teleport to fix this issue?

**Comment by ScuroK** [comment]
@dumptruckman 
Yesterday i tested xInventories and found the same bug aswell!! That means all major inventory plugins are affected! Its just a matter of time untill this bug becomes popular (youtube etc.).

After lots of testing i came up with this idea:

1. Create some kind of "dummy inventory"
2. If a player changes the world this "dummy inventory" will load first.
Its function is to act as a transit inventory. If the player uses this bug, the cheated items go into this dummy inventory. Maybe you could even block the dropping of items there. but maybe thats not needed.
3. After a short delay the "dummy inventory" gets cleared and the real inventory loads.

i would do it myself but im not a dev.
And its quite sad to see all the developers of inventory plugins became lazy and inactive...

**Comment by dumptruckman** [comment]
@ScuroK When a bug as devastating as this is *easily* exploited, it's very easy to lose heart in a project. I wouldn't be surprised if the other inventory plugin devs have experienced the same thing. In fact, I decided this plugin was officially dead as long as this exploit exists.

Now, the question is, are you using the latest dev builds? The fix I implemented caused me to be unable to reproduce the issue on a server where I could reproduce it very easily.

**Comment by Gnat008** [comment]
Heya, PWI guy here. Currently I close the inventory on teleport as you do, and clear everything again before loading the new one. I suppose the question now is if that was indeed the root problem, or if something else is going on. It's a weird one, for sure.

**Comment by ScuroK** [comment]
@dumptruckman you wer not able to reproduce the bug doesnt man you fixed it.
If closing the inventory is the only thing you did, then it means this bug is not fixed. Because Gnat did the exact same thing in PWI.

Let me give you an example:
On one server it took me much longer to reproduce it than on another server. So i thought this server had it fixed. But i was bored and i had time so i kept trying for 10 more min and BAM i got my diamonds.

I also suggested how probably fix this bug multiple times. i told it here, i told it to @Gnat008  and i told it to the developer of xInventories: Try to let an extra "dummy inventory" eat those cheated items first, then switch to the actual inventory. From my point of view this makes sence or lets say it is at least worth trying. Or isn't it?

**Comment by ScuroK** [comment]
@dumptruckman and yes: i did use the latest snapshot. it was easy AF to glitch the items over..

**Comment by dumptruckman** [comment]
Please share the information that `/mvv -g` gives you on server console.

**Comment by ScuroK** [comment]
[14:29:50 INFO]: [Multiverse-Inventories] Multiverse-Inventories Version: 2.5.0-SNAPSHOT-b444
[14:29:50 INFO]: [Multiverse-Inventories] First Run: false
[14:29:50 INFO]: [Multiverse-Inventories] Using Bypass: false
[14:29:50 INFO]: [Multiverse-Inventories] Default Ungrouped Worlds: false
[14:29:50 INFO]: [Multiverse-Inventories] Using GameMode Profiles: false
[14:29:50 INFO]: [Multiverse-Inventories] === Groups ===
[14:29:50 INFO]: [Multiverse-Inventories] default: {Worlds: [world, world_the_end, world_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[14:29:50 INFO]: [Multiverse-Inventories] welt: {Worlds: [world], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[14:29:50 INFO]: [Multiverse-Inventories] nether: {Worlds: [world_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core] Multiverse-Core Version: 2.5.1-SNAPSHOT-b730
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core] Bukkit Version: git-Spigot-bb614f8-e40c9ef (MC: 1.12.2)
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core] Loaded Worlds: [{"MVWorld@641451617":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_the_end"}}, {"MVWorld@822412968":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}, {"MVWorld@879607512":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_nether"}}, {"MVWorld@1108451448":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"DoctorWhoThemeInMinecraft"}}]
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core] Multiverse Plugins Loaded: 1
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core] Economy being used: Essentials Economy
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core] Dumping Config Values: (version 2.9)
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core]  messagecooldown: 5000
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core]  teleportcooldown: 1000
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core]  worldnameprefix: true
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core]  worldnameprefixFormat: [%world%]%chat%
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core]  enforceaccess: false
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core]  displaypermerrors: true
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core]  teleportintercept: true
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core]  firstspawnoverride: true
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core]  firstspawnworld: world
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core]  debug: 0
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Core] Special Code: FRN002
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Inventories] Multiverse-Inventories Version: 2.5.0-SNAPSHOT-b444
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Inventories] First Run: false
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Inventories] Using Bypass: false
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Inventories] Default Ungrouped Worlds: false
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Inventories] Using GameMode Profiles: false
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Inventories] === Groups ===
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Inventories] default: {Worlds: [world, world_the_end, world_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Inventories] welt: {Worlds: [world], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[14:29:50 INFO]: [Multiverse-Core] [Multiverse-Inventories] nether: {Worlds: [world_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[14:29:52 INFO]: [Multiverse-Core] Version info dumped here: http://j.mp/2qEL9Sq

>

**Comment by ScuroK** [comment]
@dumptruckman maybe you used some per-gamemode-inventory options when you tested it? This would hide the bug because it would act similar to what i suggested: one inventory would eat the glitched items before switcheing to the actual inventory. but im not sure about this. 

it tested it on my local server and had no problems to glitch items over...

**Comment by ScuroK** [comment]
i just found that even this plugin (which uses player.dat files in the world folders) is affected by this bug awell:
https://www.spigotmc.org/resources/myworlds.39594/

**Comment by bergerkiller** [comment]
Just to pitch in too (what a party!), this is almost certainly a server-side bug. I'll look into it tomorrow, set up some packet listeners on SET_CREATIVE_SLOT, and see how it goes. My assumption is that the server is accepting creative mode set slot packets during a very short time-frame the player is joining a new world. This is likely outside the reach of plugins with bukkit alone, but can be worked around by catching and cancelling the SET_CREATIVE_SLOT packets during a world change.

**Comment by ScuroK** [comment]
@bergerkiller thank you so much for trying to fix this digusting bug! Hope you can find a way! If you need intensive testing, feel free to contact me on spigot ok?

**Comment by dumptruckman** [comment]
@bergerkiller to be honest, I suspected the same thing very early on. I believe I even opened a ticket for craftbukkit and they closed it saying it was caused by my plugin not handling it appropriately.

**Comment by Dreadonator** [comment]
What do you think about loading an empty inv first and then lod the real one after with some delay?

**Comment by bergerkiller** [comment]
@dumptruckman 
My independent testing showed the same thing. The first time you open a creative inventory, the client sends set slot packets for all items in your inventory. It is more than possible to trigger clients into sending creative mode set slot packets while he is in survival mode on the server. I couldn't reproduce it yet, so its a timings problem, but it certainly looks that way. With modded clients that send waves of set slot packets this glitch can easily be exploited to give yourself any items you want.

I'm working with ScuroK to properly reproduce and diagnose the problem.

**Comment by ScuroK** [comment]
i didnt need a modded client at all. And i tested it on many different servers. i have a normal network aswell. And i know other users tested it too. 

Further im not sure if its a creative-only problem. tonight i will test if it works betweed 2 survival-worlds aswell.

Last but not least i would appreciate if you guys could comment on my suggestion how to fix this issue. Idk why everybody ignores my suggestion of having some delay and an empty inventory between.

**Comment by bergerkiller** [comment]
@ScuroK 
Im ignoring your suggestion because it doesnt diagnose the actual problem. The actual problem is the client itself sending inventory items/contents using SET_SLOT as if in creative mode. This is like giving yourself items in the ingame menu. You can empty out the inventory, but that doesnt actually fix it, because players can use a modded client to send these packets anyways.

**Comment by bergerkiller** [comment]
After going through the server source, one possibility I see is that on the server side there is a tiny timeframe where a different instance of EntityPlayer is used, potentially caused by the world change. This may cause the game mode that is set to be incorrect, allowing the change through. It seems extremely unlikely this is caused by the plugins themselves, because the inventory contents are set after the game mode change. Its impossible.

**Comment by Dreadonator** [comment]
Thanks for explaining. But the bug does not appear if i use the per-gamemode AND the per-world inventory options. Because one will work similar like a dummy inventory.

I know my suggestion doenst fix the root of the problem. But i thinks its worth to try a workaround for now rather than giving up my server concept :/

**Comment by bergerkiller** [comment]
Wait, so you are letting the game mode change be managed by a different plugin than you have the inventory managed? Thats bound to cause race conditions where the inventory is loaded before the game mode change...

**Comment by Dreadonator** [comment]
Ok but is this also the case if both worlds are in rhe same gamemode? Or if i am in the same gamemode?

**Comment by Dreadonator** [comment]
I will test this out aswell tonite, to see if you are right

**Comment by bergerkiller** [comment]
This issue only happens when a player was in a creative game mode before and moves to a world where that isnt the case. It probably also happens when you switch between creative worlds, but thats obviously less of a problem.

**Comment by Gnat008** [comment]
If the proper fix to this is in the server itself as we all suspect, we should all note that it will only ever (maybe) be fixed in a newer version; none of the current versions of Spigot being used will ever see this fix. So regardless, we'll all probably need a workaround in our plugins of some sort, much as I hate janky hacks to work around server bugs.

**Comment by bergerkiller** [comment]
Currently testing out a timeout put on the creative inventory slot packet after a player changes worlds. If it works, it works, and it has minimal harm to other plugins. If more plugins do the same thing, it doesn't really matter because every plugin will expire the timeout at some point.

Just a quick hackjob
https://hastebin.com/evosonubew.java

**Comment by dumptruckman** [comment]
@bergerkiller question is, can you reproduce the bug? I cannot, not after my last "fix".

**Comment by bergerkiller** [comment]
Nope, Im letting someone else fix it for that reason. Im fairly sure its caused because different plugins handle different steps of the process. For example, I receive the world change event but dont change the game mode, someone else does. Then it can happen that the game mode is changed too late by the other plugin, and now you have a bug. For sure the changing of the game mode of the player and when this happens has a big impact.

**Comment by dumptruckman** [comment]
Multiverse-Core is the most likely thing to be changing the game mode on world change I would think. I wonder if MV-Core were to change it on teleport monitor instead of world change if that would solve the problem.

**Comment by ScuroK** [comment]
Ok guys i finished testing with Multiverse-Core and a snapshot of MyWorlds by @bergerkiller 
(No MV-INV !)

teleporting from survival to survival didnt create the glitch anymore with the latest build of MyWorlds. But when i do it from creative to survival it did. BUT i could not use the glitched items! when i clicked on them they disappeared (like ghost items).

Both worlds were survival by default. i just used /gm 1 in one world to test it.

However i do know that the glitched items CAN be taken and used if i do the same thing with MV-INV and PWI. I guess this has something to do with the differences between those plugins.

my worlds.ylm (Multiverse-Core):
https://pastebin.com/DiPBdwPY

my MultiverseCore-config:
https://pastebin.com/YsuJWuUq

my MyWorlds-config:
https://pastebin.com/z8S9XgjV

**Comment by ScuroK** [comment]
@dumptruckman so you think by changing the way multiverse-core works, the bug could be fixed?
If so thats a good point. Because i tested so many different inventory plugins but always used multiverse-core :D

**Comment by bergerkiller** [comment]
Its not surprising that ghost items happen when its fixed. The client is trying to force the use of an invalid inventory, and if the server doesn't detect this, the server won't resend the mismatched icons. Ghost items are no harm though, players shouldn't be messing with their inventory right after a teleport anyways.

I'm happy to hear my patch overall worked. The patch IS kind of nasty though. I just disable creative-mode inventory actions for a couple ticks after changing the inventory of the player.

**Comment by ScuroK** [comment]
i dont consider the ghost items to be a problem. because this bug does most likely not appear during normal gameplay. it will most likely happen if players try this intentionally. 

@bergerkiller seriously its 1000times better to get a "Nasty patch" rather than no patch at all! Do you think the same patch can be applied to mvinv and pwi?

**Comment by bergerkiller** [comment]
Sure, but that's up to them whether they want to or not. They might not consider this too big of an issue, or consider it a 'plugin conflict' of sorts. All they have to do is store a timeout int value for players when they change their inventory, have some tick task count it down (and remove it when its 0). Then have a packet listener cancel creative inventory slot packets while this timeout is set.

**Comment by Gnat008** [comment]
> have some tick task count it down (and remove it when its 0).

Would just a delayed task also work instead of using a task timer?

**Comment by bergerkiller** [comment]
It would, but that adds a lot of complexity of properly cancelling the task when the player leaves the server / when the player switches world again / etc.

This is how I do it right now:
https://hastebin.com/lunurujocu.java

With setTimeout called when I change the inventory, and clearTimeout called when players join/quit as a safety measure / anti-memory leak.

**Comment by ScuroK** [comment]
and when i tested it i didnt recognize or "feel" any kind of disturbing delay. I dint think players will feel it.

**Comment by dumptruckman** [comment]
The problem I have with this fix is relying on protocol stuff. Such a fix would require manual updates with every new version of Minecraft which I'm not too keen on having to produce.

**Comment by ScuroK** [comment]
A fix is always better than abandon a project isnt it? 

Ok dont laugh on me (im not a dev) but could it help to use protocollib as a dependency?

**Comment by dumptruckman** [comment]
That would just mean I would have to update for each new version of ProtocolLib. I have some ideas for fixes but unfortunately, I cannot implement them right now.

**Comment by ScuroK** [comment]
hmm. ok. I hope you guys dont take me wrong if i stress this issue so much. i know i didnt pay for any inventory plugins (of course iw ould if they were premium). But the point is, there are only 3 or 4 inventory plugins out there. If they all can be bypassed so easily it means all those multi-world servers are ****. and they will only have choice between closing worlds or using bungee cord. Many small server cant simply change to a bungeecord network. the result is: more giants like hypixel and less creative little community servers.

@dumptruckman what ideas do you have?

**Comment by bergerkiller** [comment]
@dumptruckman 
This is true. For me it does not matter terribly much, because BKCommonLib supports Minecraft 1.8 through 1.12.2 all at once with the latest version. But of course, things like this can break in the future.

**Comment by bergerkiller** [comment]
Pushed all that is needed to "patch" it to my repo in this file. All thats needed is to enable/disable and call setTimeout when changing inventories.

https://github.com/bergerhealer/MyWorlds/blob/master/src/main/java/com/bergerkiller/bukkit/mw/MWCreativeSlotSuppressor.java

**Comment by dumptruckman** [comment]
@bergerkiller Any chance you'd be willing to create a standalone plugin that applies this fix? Would that be easy? It would be a good workaround until a server fix is found.

@ScuroK I dunno, I have a few but I don't like any of them because it all involves disabling things for an arbitrary amount of time. The problem with that is, given enough latency, your arbitrary amount of time may not be long enough.

**Comment by Gnat008** [comment]
@dumptruckman  Would that work as a standalone though? Wouldn't we still have to implement this for each of our projects?

**Comment by bergerkiller** [comment]
Thats not really possible in this case, because where and how the inventory is altered depends on the plugin doing the inventory changes. MyWorlds for example hooks into the server directly, injecting a class in the server overriding how player data is loaded and saved, to do the refreshing of the player's inventory there. Multiverse likely does something differently, I presume catching events like WorldChange. These differences in timing make it a little tricky to generally apply.

Also it wouldn't really be standalone when its dragging the entirety of BKCommonLib into the mix...
Behind that somewhat simple code lies a very large codebase:
- Listening for packets received by the server and handling them with its own proxy hook + protocollib
- Reading/writing packet fields
- Constructing packets, sending packets
- Conversion between bukkit itemstack and nms itemstack and serialized slot data
- All that supported for different versions of the server, and serverS
It takes a bit too much time for me to merge all that logic into something standalone.

**Comment by bergerkiller** [comment]
This is an attempted stand-alone version. Can someone confirm whether or not it works?
https://hastebin.com/igugehicos.java

https://www.dropbox.com/s/sv0r9q7g8mnf08x/WorldInventoriesDupingPatch-1.0.jar?dl=0

**Comment by dumptruckman** [comment]
Wouldn't it need to be on teleport (to another world) rather than world change?

**Comment by dumptruckman** [comment]
@ScuroK can you try this and let us know?

**Comment by Dreadonator** [comment]
Hey guys its me ScuroK (mobile phone). I am on the way to bed now and will be on a trip till sunday. I will be able to test it this sunday and let u know! :)

**Comment by bergerkiller** [comment]
@dumptruckman 
Unless this is another typical half-assed Bukkit event, I presumed world change event would be fired after a successful teleport to another world. For sure its fired, and it locked me out of inventory if I used a long slot timeout for testing. Adding additional cross-world checks on player move and player teleport is trivial though, but I felt it was unneeded.

**Comment by Gnat008** [comment]
@bergerkiller Using MultiVerse and PWI with this patch, I am inconsistently able to get phantom items from the creative inventory to the survival inventory. I am not sure if this is different without the patch though because when I assumed that I had successfully repro'd the issue, I didn't think to check if they were phantom items.

Testing with a block of dirt in my inventory, I am unable to even get the phantom items so far.

**Comment by bergerkiller** [comment]
Phantom items seem a bit impossible to avoid, it also happened when I handled the packet directly. Only when the items are real is there a problem I think

**Comment by Gnat008** [comment]
Agreed. It's certainly a better outcome than real items coming through.

**Comment by ScuroK** [comment]
@dumptruckman 
@bergerkiller 

I just tested Multiverse-Inventories along with "WorldInventoriesDupingPatch" and i was not able to glitch items or even get ghost items anymore! :)

thanks alot bergerkkiller!

Now i will test it with PWI.

**Comment by ScuroK** [comment]
@Gnat008 

I just tested PWI along with "WorldInventoriesDupingPatch" and i was not able to glitch items or even get ghost items anymore! :)

That means:bergerkiller is a hero! For now all inventory-plugins depend on his patch :D

**Comment by ScuroK** [comment]
Ok guys. I tested it all with and without the patch and i can confirm that this patch COMPLETELY blocks this bug! i was not even able to get the ghost items again. Not on my local server and not on my public server! :D Finally!!! Thank you so much for being so patient with me even i stressed this issue and THANK YOU to @bergerkiller for actively fixing this problem!

**Comment by bergerkiller** [comment]
Very happy to hear this patches it then! I'll roll it up into a simple to use class that people could include in PWI/multiverse and I will also include in MyWorlds. Multiple plugins including this same patch doesn't hurt, anyways.

Since this simple patch uses only Bukkit, it makes it much easier to integrate.

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/MyWorlds/blob/master/src/main/java/com/bergerkiller/bukkit/mw/patch/WorldInventoriesDupingPatch.java
Feel free to include it in multiverse.

**Comment by OpticFusion1** [comment]
This has been fixed in my fork of the plugin https://github.com/OpticFusion1/Multiverse-Inventories https://www.spigotmc.org/resources/multiverse-inventories-1-13-support.63910/ <3

**Comment by nickg2** [comment]
this is still happening to me.

**Comment by nicegamer7** [comment]
If you can record a short video showing that you are using the latest release of both MV and Minecraft, I'll reopen this issue.

**Comment by regtable** [comment]
i tried doing this with better portals add on i maybe not timining it right but cant replicate it. using paper server with mc 1.17.1 and latest mv core and inventorys and better portals 0.9 however i can do this........ not sure if thats an mv issue or better portals

https://youtu.be/3eNpyvFF8iI
