### ISSUE TITLE
Internal Error 

### ISSUE THREAD

**Issue by XRageBlazeOfficial** [Multiverse/Multiverse-Inventories#325]
an internal error occured while trying to run this command

it happes no matter which command i do 
and ive just added the plugin

**Comment by sorifiend** [comment]
That error is almost always due to one of the following reasons:
1. An outdated plugin.
2. A missing dependency (Multiverse Core?).
3. A version mismatch between server or plugins (Between multiverse core and multiverse inventories).

Make user that you have the latest server/spigot version, and the you have the latest version of both multiverse core and inventories.

Latest versions here:
Multiverse-Core-2.6.0.jar can be found here: https://ci.onarandombox.com/job/Multiverse-Core/
Multiverse-Inventories-2.5.0-SNAPSHOT.jar can be fonud here: https://ci.onarandombox.com/job/Multiverse-Inventories/
