### ISSUE TITLE
Stats folders

### ISSUE THREAD

**Issue by alexstore06** [Multiverse/Multiverse-Inventories#417]
For multiple reasons, I am unable to fill the template. I run my server through Apex Hosting, who, in turn, only allow me to access the server through Multicraft, which creates many problems.

I am running Spigot 1.16.5. I have two sets of worlds, each with a normal world, nether, and end. In each set, shares is set to all. I have had no problems with gameplay, everything seems to work fine.

However, I use a program called MinecraftStats (can be found on GitHub) to read my stats folders and create a webpage with a leaderboard. For my default set of worlds, I have no problems with this. However, as I was trying to create a second webpage for my other set of worlds, I realized that my second set of worlds _does not_ have a stats folder. Does Multiverse-Inventories no longer create seperate stats folders for separate groups? Is it just putting all the stats into one folder? I'm fine with it as long as stats are being counted, even if they're just counted with the first inventory group.

**Comment by benwoo1110** [comment]
Since you didn't fill in the template, I assuming mvinv is working properly.

The important thing to note: Player inventory, game stats and advancement are all stored and read by minecraft in the default world folder **only**. mv-inv can only swap those data out during events such as world change. Therefore, it's not possible just read data from different world folder like this. 

For having per world sharing of game stats, this still current in the works: https://github.com/Multiverse/Multiverse-Inventories/pull/363

However, if you want to read it such that even when the data is not loaded (i.e. player is not in that world), you will probably have to read it from mv-inv.

**Comment by alexstore06** [comment]
I'm afraid that I'm still thoroughly confused. Let me try to explain my questions more:

1. First, here's the MinecraftStats page: https://scholarcraftmc.com/MinecraftStats
2. Will these numbers keep counting when a user switches to my second inv group? (First group is named default, second is named anarchy)
3. If not, are those statistics just not kept, or does mvinv keep track of them?
4. If mvinv keeps track of them, how could I read them?

**Comment by benwoo1110** [comment]
For 2. Your player will always only have a single game stats data stores. When using the test build that supports game stats (#363), mv-inv only replace it with the relevant numbers stored on the world change. This means you can't just do something like want game stats world1 and world2 by reading from Minecraft. Minecraft has no knowledge of mv-inv doing the change.

For 3. if you use the test build in #363, then yes.

For 4. Probably you can use some classes in mv-inv to load from file data if you know java, tho there is little documentation on it. Well doing more APIs and documentation will help but dev time is very limit atm and it's up to @dumptruckman as well.

**Comment by alexstore06** [comment]
That clears things up, tysm!
