### ISSUE TITLE
Gettin an error when changing the world

### ISSUE THREAD

**Issue by Alcrafter-YT** [Multiverse/Multiverse-Inventories#439]
### Information

* **Server version:** 
Server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

* **Full output of `/mv version -p`:**
https://pastebin.com/3q9M7rtv

* **Server log:**
https://pastebin.com/7Jreepic
Error here:
https://pastebin.com/nh2aTUEs

### Help request

**Problem**
I'm getting an error when I change the world with /mvtp. And I don't know how to fix that.

**What I have tried**
1. Checked if the newest Plugin version would fix (it didn't load)
2. Changed the version to join with (I'm using ViaVersion)
3. Changed Java Version from 11 to 8 and back (didn't fix it)

**Screenshots**
All the errors are in the log

**Comment by benwoo1110** [comment]
`Caused by: java.lang.IllegalStateException: getBalance is only available when using an economy plugin with Vault`

You do not have an an economy plugin with Vault. Check that your economy and vault plugin are both working correctly. If you enabled the ECONOMY sharable by mistake, run '/mvinv toggle economy' to resolve this.
