### ISSUE TITLE
Multiverse Inventories is crashing on startup (PaperMC 1.18.1)

### ISSUE THREAD

**Issue by HenrikoMagnifico** [Multiverse/Multiverse-Inventories#485]
### Information

* **Server version:** git-Paper-152 (MC: 1.18.1)

* **Full output of `/mv version -p`:** [https://j.mp/3ruGONv](https://j.mp/3ruGONv)

* **Server log:** [https://pastes.dev/zPzSS8W14U](https://pastes.dev/zPzSS8W14U)

### Details
I **was** able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods. On my own server, before I noticed the error, it had been working fine for the last couple of months, but only a few days ago I noticed it had stopped working and now produces an error. There are no other plugins than Multiverse Core/Inventories/Portals/Nether Portals, and deleting the whole Multiverse-Inventories folder does not resolve the issue either.
Updating to the latest version of Multiverse-Core/Inventories/Portals/Nether Portals doesn't fix it either, Multiverse-Inventories is still red and fails to load. Deleting the whole Multiverse-Core folder fixes the issue, but results in players losing their inventory data, which means it's not a viable solution.

**Description**  
Multiverse-Inventories fails to load on startup and produces an error, resulting in the plugin not working at all.

**Steps to reproduce**  
Make a server with Multiverse-Inventories and the other Multiverse Plugins on PaperMC using the same version and the included Multiverse-Inventories folder.

**Expected behavior**  
For Multiverse-Inventories to load successfully.

**Screenshots**  
![Skärmbild 2022-01-18 132747](https://user-images.githubusercontent.com/11783274/149937379-18fe3bad-9675-4c48-a4d4-14e8af63cde7.png)

[Multiverse-Inventories Configuration.zip](https://github.com/Multiverse/Multiverse-Inventories/files/7889107/MVI.zip)

**Comment by Prismism0** [comment]
I have run into this same problem today. I was able to perform the following steps to get it back in working condition (NOTE: these steps may not **all** be necessary but this is just exactly what I did before it started working):

1. Make a backup of the Multiverse-Inventories folder, so I don't risk losing player data.
2. Delete the Multiverse-Inventories folder.
3. Start the server
4. At this point, the plugin loads correctly, but obviously I have no world groups set up as I did before.
4. Stop the server
4. Replace the newly generated config.yml and groups.yml with the ones from my backup folder.
5. Notice that these files that I just copied over have thousands of lines. There seems to be a bug which duplicates whitespace and comment lines on server startup.
6. Remove all comment lines and all extraneous whitespace from both files.
7. Start the server
8. Stop the server
9. Drop in the groups, players, and worlds folders from the backup
10. Start the server
11. Now the plugin still loads correctly AND I have configuration and player data back to the way it was. Victory!

Notice how the config.yml and groups.yml files in the ZIP provided by @HenrikoMagnifico have 51k and 24k lines, respectively. Given that most of it is whitespace, they are not actually very large files, but I could imagine that depending on how the YAML parser is written, this could give it a hard time. So that's my best guess!

Why the plugin basically doubles the size of the YAML files every time on startup, I'm not sure. But it's probably necessary to go through and trim them back down every so often, depending on how often you restart your server.

**Comment by HenrikoMagnifico** [comment]
Update: The issue started happening again this morning. It seems to re-occur every couple of days / weeks for no clear reason.

**Comment by nicegamer7** [comment]
This looks to be a combination of #437 (fixed in our snapshots), and #480 (will be fixed soon). We hope to publish a new release after it's fixed.

For now there is an up-to-date build in #483 that fixes the issue.
